# Internal microphone on a ThinkPad X1 Gen7
recorder: ["ffmpeg", "-f", "alsa", "-channels", "4", "-i", "hw:CARD=sofhdadsp,DEV=7"]
# Speak via Sound Open Firmware ALSA PCM device with 220 WPM
speaker: ["espeak-ng", "-d", "plughw:sofhdadsp", "-a", "75", "-s", "220"]
chat:
  model: gpt-4
  temperature: 0.8
  messages: []
chat_functions:
- haskell
- localTime
- metar
transcription:
  model: whisper-1
